# Generated by Django 5.0.1 on 2024-01-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_usuario_first_name_remove_usuario_last_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
