# Generated by Django 5.0.1 on 2024-02-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usuario_cnpj_usuario_first_name_usuario_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='razao_social',
        ),
    ]
