# Generated by Django 5.0.1 on 2024-02-08 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_usuario_cnpj_remove_usuario_razao_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
