# Generated by Django 5.0.1 on 2024-02-19 17:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=150)),
                ("password", models.CharField(default="", max_length=200)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "critica",
                    models.CharField(
                        max_length=1000, null=True, verbose_name="crítica"
                    ),
                ),
                (
                    "data_envio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de envio"
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "avaliado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estacionamento_avaliado",
                        to="empresas.perfillocal",
                        verbose_name="avaliado",
                    ),
                ),
            ],
            options={
                "verbose_name": "avaliação de usuários",
                "verbose_name_plural": "avaliações de usuários",
                "ordering": ["data_envio"],
            },
        ),
    ]
