# Generated by Django 5.0.1 on 2024-02-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['username']},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='senha',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_nasc',
        ),
    ]
