# Generated by Django 5.0.1 on 2024-01-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='sobrenome',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_nasc',
            field=models.DateField(default='', verbose_name='data de nascimento'),
        ),
    ]
