# Generated by Django 5.0.1 on 2024-02-19 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cliente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="avaliador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cliente_avaliador",
                to="clientes.cliente",
                verbose_name="avaliador",
            ),
        ),
    ]
