# Generated by Django 4.2.10 on 2024-02-12 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacionamento_avaliado', to='empresas.estacionamento', verbose_name='avaliado'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_avaliador', to='clientes.cliente', verbose_name='avaliador'),
        ),
    ]
