# Generated by Django 5.0.1 on 2024-01-30 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_sobrenome_cliente_cpf_cliente_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
    ]
