# Generated by Django 5.0.1 on 2024-02-08 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_rename_password_cliente_senha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome']},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='username',
            new_name='nome',
        ),
    ]
