# Generated by Django 5.0.1 on 2024-01-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_cpf_alter_cliente_data_nasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_nasc',
            field=models.DateTimeField(auto_now=True, verbose_name='data de nascimento'),
        ),
    ]
