# Generated by Django 5.0.1 on 2024-02-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_tipo_usuario_cliente_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='senha',
            new_name='password',
        ),
        migrations.AddField(
            model_name='cliente',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
