# Generated by Django 5.0.1 on 2024-02-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENTE', 'Cliente'), ('ESTACIONAMENTO', 'Estacionamento')], max_length=50),
        ),
    ]
