# Generated by Django 5.0.1 on 2024-02-09 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_alter_cliente_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
    ]
