# Generated by Django 4.2.10 on 2024-02-19 11:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.PositiveSmallIntegerField()),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Endereço',
            },
        ),
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome_fantasia', models.CharField(max_length=200, unique=True, verbose_name='Nome Fantasia')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('password', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietarios', models.CharField(blank=True, max_length=200, null=True)),
                ('coberto', models.BooleanField(default=False)),
                ('valor', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='valor (R$/h)')),
                ('dias_aberto', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')], max_length=13)),
                ('descricao', models.TextField(max_length=250, verbose_name='descrição')),
                ('hora_abre', models.TimeField(blank=True)),
                ('hora_fecha', models.TimeField(blank=True)),
                ('vagas_total', models.PositiveSmallIntegerField()),
                ('vagas_pref', models.PositiveSmallIntegerField()),
                ('vagas_cob', models.PositiveSmallIntegerField()),
                ('vagas_disp', models.PositiveSmallIntegerField()),
                ('nota_media', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='nota média')),
                ('estacionamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_perfil', to='empresas.estacionamento')),
            ],
            options={
                'verbose_name_plural': 'Perfis de locais',
            },
        ),
    ]
