# Generated by Django 4.2.10 on 2024-02-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.PositiveSmallIntegerField()),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
            ],
        ),
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome_fantasia', models.CharField(max_length=200, unique=True, verbose_name='Nome Fantasia')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('password', models.CharField(default='', max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietarios', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('segunda', models.BooleanField(default=False)),
                ('terca', models.BooleanField(default=False)),
                ('quarta', models.BooleanField(default=False)),
                ('quinta', models.BooleanField(default=False)),
                ('sexta', models.BooleanField(default=False)),
                ('sabado', models.BooleanField(default=False)),
                ('domingo', models.BooleanField(default=False)),
                ('coberto', models.BooleanField(default=None)),
                ('valor', models.FloatField(default=0)),
                ('descricao', models.TextField(default='', max_length=250, verbose_name='descrição')),
                ('hora_abre', models.TimeField(blank=True, default='')),
                ('hora_fecha', models.TimeField(blank=True, default='')),
                ('vagas_total', models.PositiveSmallIntegerField()),
                ('vagas_pref', models.PositiveSmallIntegerField()),
                ('vagas_cob', models.PositiveSmallIntegerField()),
                ('vagas_disp', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
