# Generated by Django 5.0.1 on 2024-02-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfillocal',
            name='coberto',
            field=models.CharField(default=None, max_length=1, verbose_name='dias abertos'),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='descricao',
            field=models.TextField(default='', max_length=250, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='valor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='perfillocal',
            name='dias_abertos',
            field=models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default=1, max_length=7, verbose_name='dias abertos'),
        ),
    ]
