# Generated by Django 5.0.1 on 2024-02-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfillocal',
            name='nome_estacionamento',
            field=models.CharField(default=1, max_length=250, verbose_name='nome_estacionamento'),
            preserve_default=False,
        ),
    ]
