# Generated by Django 5.0.1 on 2024-01-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamento',
            name='usuario',
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='senha',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='nome_fantasia',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
    ]
