# Generated by Django 5.0.1 on 2024-02-10 20:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamento',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='perfillocal',
            name='dias_abertos',
        ),
        migrations.RemoveField(
            model_name='perfillocal',
            name='local',
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='coberto',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='descricao',
            field=models.TextField(default='', max_length=250, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='proprietario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='empresas.estacionamento'),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='quarta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='quinta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='segunda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='sexta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='terca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='valor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='local',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='nome_fantasia',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='razao_social',
            field=models.CharField(max_length=200, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='perfillocal',
            name='hora_abre',
            field=models.TimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='perfillocal',
            name='hora_fecha',
            field=models.TimeField(blank=True, default=''),
        ),
    ]
