# Generated by Django 5.0.1 on 2024-01-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_remove_estacionamento_usuario_estacionamento_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='email',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='nome_fantasia',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='razao_social',
            field=models.CharField(max_length=200, verbose_name='Razão social'),
        ),
    ]
