# Generated by Django 5.0.1 on 2024-02-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estacionamento",
            name="cnpj",
            field=models.CharField(max_length=18, verbose_name="CNPJ"),
        ),
        migrations.AlterField(
            model_name="estacionamento",
            name="email",
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name="estacionamento",
            name="nome_fantasia",
            field=models.CharField(max_length=200, verbose_name="Nome Fantasia"),
        ),
    ]
