# Generated by Django 5.0.1 on 2024-02-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_endereco_proprietarios"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perfillocal",
            options={
                "verbose_name": "Perfil Local",
                "verbose_name_plural": "Perfis Locais",
            },
        ),
    ]
