# Generated by Django 5.0.1 on 2024-02-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_remove_estacionamento_senha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfillocal',
            name='proprietario',
        ),
        migrations.AddField(
            model_name='endereco',
            name='proprietarios',
            field=models.ManyToManyField(related_name='estacionamentos', to='empresas.perfillocal'),
        ),
    ]
