# Generated by Django 5.0.1 on 2024-02-06 01:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_perfillocal_coberto_perfillocal_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfillocal',
            name='hora_abre',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
