# Generated by Django 5.0.1 on 2024-01-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_estacionamento_cnpj_alter_estacionamento_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfillocal',
            name='hora_abre',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='hora_fecha',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='vagas_cob',
            field=models.PositiveSmallIntegerField(default=''),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='vagas_disp',
            field=models.PositiveSmallIntegerField(default=''),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='vagas_pref',
            field=models.PositiveSmallIntegerField(default=''),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='vagas_total',
            field=models.PositiveSmallIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='perfillocal',
            name='descricao',
            field=models.CharField(default='', max_length=1000, null=True, verbose_name='sobre'),
        ),
        migrations.AlterField(
            model_name='perfillocal',
            name='dias_abertos',
            field=models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default='', max_length=7, verbose_name='dias abertos'),
        ),
    ]
