# Generated by Django 5.0.1 on 2024-02-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_remove_endereco_logradouro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='numero',
        ),
    ]
