# Generated by Django 5.0.1 on 2024-02-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "empresas",
            "0003_alter_estacionamento_cnpj_alter_estacionamento_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="endereco",
            name="proprietarios",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
