# Generated by Django 5.0.1 on 2024-02-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_remove_perfillocal_proprietario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='proprietarios',
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='proprietarios',
            field=models.ManyToManyField(related_name='estacionamentos', to='empresas.perfillocal'),
        ),
    ]
