# Generated by Django 5.0.1 on 2024-02-23 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_remove_endereco_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfillocal',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='empresas.endereco'),
            preserve_default=False,
        ),
    ]
