# Generated by Django 5.0.1 on 2024-01-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_perfillocal_hora_abre_perfillocal_hora_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfillocal',
            name='vagas_cob',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='perfillocal',
            name='vagas_disp',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='perfillocal',
            name='vagas_pref',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='perfillocal',
            name='vagas_total',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
    ]
