# Generated by Django 5.0.1 on 2024-02-06 01:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_alter_perfillocal_hora_abre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfillocal',
            name='hora_abre',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
