# Generated by Django 5.0.1 on 2024-02-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_remove_endereco_proprietarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamento',
            name='proprietarios',
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='proprietarios',
            field=models.CharField(default='', max_length=200),
        ),
    ]
