# Generated by Django 5.0.1 on 2024-02-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_perfillocal_hora_abre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfillocal',
            name='local',
        ),
        migrations.AlterField(
            model_name='perfillocal',
            name='coberto',
            field=models.CharField(default=None, max_length=7, verbose_name='dias abertos'),
        ),
        migrations.AlterField(
            model_name='perfillocal',
            name='hora_abre',
            field=models.TimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='perfillocal',
            name='hora_fecha',
            field=models.TimeField(blank=True, default=''),
        ),
    ]
