# Generated by Django 5.0.1 on 2024-02-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_remove_estacionamento_proprietarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfillocal',
            name='proprietarios',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
