# Generated by Django 5.0.1 on 2024-01-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_perfillocal_vagas_cob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfillocal',
            name='vagas_cob',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='perfillocal',
            name='vagas_disp',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='perfillocal',
            name='vagas_pref',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='perfillocal',
            name='vagas_total',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
