# Generated by Django 5.0.1 on 2024-02-23 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_alter_perfillocal_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfillocal',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='empresas.endereco'),
        ),
    ]
