# Generated by Django 5.0.1 on 2024-02-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_alter_perfillocal_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfillocal',
            name='endereco',
        ),
    ]
