# Generated by Django 5.0.1 on 2024-01-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_alter_perfillocal_vagas_cob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfillocal',
            name='vagas_disp',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='perfillocal',
            name='vagas_pref',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='perfillocal',
            name='vagas_total',
            field=models.IntegerField(default='1'),
        ),
    ]
