# Generated by Django 5.0.1 on 2024-02-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_alter_perfillocal_coberto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfillocal',
            name='coberto',
            field=models.BooleanField(default=None, verbose_name='coberto'),
        ),
    ]
