# Generated by Django 5.0.1 on 2024-02-23 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_remove_perfillocal_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfillocal',
            name='endereco',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresas.endereco'),
            preserve_default=False,
        ),
    ]
