# Generated by Django 5.0.1 on 2024-02-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_alter_perfillocal_dias_abertos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='local',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='perfillocal',
            name='coberto',
            field=models.BooleanField(default=None),
        ),
    ]
