# Generated by Django 5.0.1 on 2024-01-31 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_alter_perfillocal_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfillocal',
            name='vagas_cob',
        ),
    ]
