# Generated by Django 5.0.1 on 2024-02-23 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_perfillocal_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfillocal',
            name='nota_media',
            field=models.FloatField(blank=True, default=None, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='nota média'),
        ),
    ]
