# Generated by Django 5.0.1 on 2024-02-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_alter_endereco_local_alter_perfillocal_coberto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfillocal',
            name='dias_abertos',
            field=models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10),
        ),
    ]
