# Generated by Django 5.0.1 on 2024-02-08 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_opcao_selecao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selecao',
            name='opcoes',
        ),
        migrations.DeleteModel(
            name='Opcao',
        ),
        migrations.DeleteModel(
            name='Selecao',
        ),
    ]
