# Generated by Django 5.0.1 on 2024-02-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0014_remove_selecao_opcoes_delete_opcao_delete_selecao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
    ]
