# Generated by Django 5.0.1 on 2024-02-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0015_alter_estacionamento_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
