# Generated by Django 5.0.1 on 2024-02-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0016_alter_estacionamento_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estacionamento',
            old_name='senha',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='nome_fantasia',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='razao_social',
            field=models.CharField(max_length=200, verbose_name='Razão Social'),
        ),
    ]
