# Generated by Django 5.0.1 on 2024-02-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0017_rename_senha_estacionamento_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamento',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
