# Generated by Django 5.0.1 on 2024-02-08 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0018_estacionamento_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamento',
            name='last_login',
        ),
    ]
