# Generated by Django 5.0.1 on 2024-02-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0020_estacionamento_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamento',
            name='senha',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
