# Generated by Django 5.0.1 on 2024-02-09 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_estacionamento_senha_alter_estacionamento_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamento',
            name='usuario',
            field=models.ForeignKey(choices=[('ADMIN', 'Admin'), ('CLIENTE', 'Cliente'), ('ESTACIONAMENTO', 'Estacionamento')], default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
