# Generated by Django 5.0.1 on 2024-02-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0022_estacionamento_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamento',
            name='senha',
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
