# Generated by Django 5.0.1 on 2024-02-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0025_remove_estacionamento_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfillocal',
            name='dias_abertos',
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='quarta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='quinta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='segunda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='sexta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfillocal',
            name='terca',
            field=models.BooleanField(default=False),
        ),
    ]
